In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("Iris.csv")

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
#check null values
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [9]:
df['Species'].unique() #finding unique val

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [10]:
df['Species'].value_counts() #find count of obs

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [12]:
#Splitting the data
x=df.iloc[:,1:5]
print(x.head())
y=df['Species']


   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2


In [15]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=21)

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:

le = LabelEncoder() # initialize the lib

In [37]:
ytrain=le.fit_transform(ytrain)
ytrain

array([0, 2, 1, 0, 2, 1, 1, 2, 0, 2, 2, 2, 2, 1, 2, 0, 0, 0, 1, 0, 1, 0,
       1, 2, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 0, 0, 2, 1, 0,
       2, 1, 2, 0, 2, 0, 0, 1, 2, 1, 1, 0, 2, 1, 0, 2, 1, 1, 2, 1, 2, 1,
       2, 2, 0, 0, 2, 2, 0, 1, 2, 1, 1, 2, 1, 2, 0, 2, 2, 0, 0, 1, 2, 0,
       0, 1, 2, 0, 0, 1, 2, 2, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 1, 1, 2, 2,
       2, 1, 2, 1, 1, 2, 2, 0, 0, 1])

In [38]:
ytest=le.transform(ytest)
ytest

array([1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0, 1, 2, 1, 0, 2, 2, 1,
       1, 1, 0, 1, 0, 0, 1, 2])

In [17]:
#ANN-CLASSIFICATION
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [39]:
model=Sequential()
model.add(Dense(4,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(26,activation='relu'))# num of hidden layers is based on trial and error
model.add(Dense(3,activation='softmax')) #based on classes - 3 op class,multiclass-softmax, 1 value- linear, 2-sigmoid

In [40]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [28]:
#linear reg=linear,mse
#multiclass classify- softmax,sparse_categorical_crossentropy
#binary- cat or dog ,  - signmoid, binary_crossentropy

In [41]:
model.fit(xtrain,ytrain,batch_size=4,epochs=15,validation_data=(xtest,ytest))

Epoch 1/15
30/30 [==============================] - 1s 12ms/step - loss: 1.0685 - accuracy: 0.4500 - val_loss: 0.9152 - val_accuracy: 0.7667
Epoch 2/15
30/30 [==============================] - 0s 3ms/step - loss: 0.8554 - accuracy: 0.6083 - val_loss: 0.7256 - val_accuracy: 0.7667
Epoch 3/15
30/30 [==============================] - 0s 3ms/step - loss: 0.6987 - accuracy: 0.7500 - val_loss: 0.5906 - val_accuracy: 0.9000
Epoch 4/15
30/30 [==============================] - 0s 3ms/step - loss: 0.5684 - accuracy: 0.8500 - val_loss: 0.4678 - val_accuracy: 0.9333
Epoch 5/15
30/30 [==============================] - 0s 3ms/step - loss: 0.4330 - accuracy: 0.9167 - val_loss: 0.3677 - val_accuracy: 0.9333
Epoch 6/15
30/30 [==============================] - 0s 3ms/step - loss: 0.3161 - accuracy: 0.9750 - val_loss: 0.2594 - val_accuracy: 0.9333
Epoch 7/15
30/30 [==============================] - 0s 3ms/step - loss: 0.2423 - accuracy: 0.9583 - val_loss: 0.2004 - val_accuracy: 0.9000
Epoch 8/15
30/30 [=

In [45]:
y_pred=model.predict([[5.5,2.3,5.6,7.4]])
y_pred #prints 3 probability value

1/1 [==============================] - 0s 38ms/step


array([[1.0093578e-06, 1.7123470e-03, 9.9828666e-01]], dtype=float32)

In [46]:
np.argmax(y_pred)   #virginica

2